services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: DockerFile
      args:
        - NODE_ENV=development
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    volumes:
      - ./apps/frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:${BACKEND_PORT:-3000}/api
      - VITE_HOST=0.0.0.0
      - VITE_PORT=3001
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 3001

  backend:
    build:
      context: ./apps/backend
      dockerfile: DockerFile
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./apps/backend:/app
      - backend_node_modules:/app/node_modules
      - ./apps/backend/database:/app/database
    environment:
      - PORT=${BACKEND_PORT:-3000}
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-traffic_analysis_db}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
    depends_on:
      - postgres
      - kafka
    networks:
      - app-network
    restart: unless-stopped
    command: sh -c "npm run db:migrate && npm run db:seed:all && npm run start"

  postgres:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-traffic_analysis_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@test.com}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - app-network
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    networks:
      - app-network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9092"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  frontend_node_modules:
  backend_node_modules:

# To find db ip-address for connection
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' traffic-analysis-system-postgres-1
# 172.22.0.2