FROM node:23-slim

WORKDIR /app

COPY package.json package-lock.json ./

# Install deps
RUN npm install && npm cache clean --force

COPY . .

# Set environment for development
ENV NODE_ENV=development

# Start development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3001"]

